-- MySQL Script generated by MySQL Workbench
-- 04/02/15 10:46:34
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema localizesenac
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `localizesenac` DEFAULT CHARACTER SET utf8 ;
USE `localizesenac` ;

-- -----------------------------------------------------
-- Table `localizesenac`.`aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `localizesenac`.`aluno` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `matricula` VARCHAR(20) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `senha` VARCHAR(80) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `nome` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `celular` VARCHAR(40) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `email` VARCHAR(200) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `ativo` ENUM('N','S') CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL DEFAULT 'N',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `NR_MATRICULA` (`matricula` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `localizesenac`.`disciplina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `localizesenac`.`disciplina` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `creditos` TINYINT(4) NULL DEFAULT '4',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `localizesenac`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `localizesenac`.`categoria` (
  `id` INT(11) NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `parametro_imagem` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `localizesenac`.`unidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `localizesenac`.`unidade` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(40) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `endereco` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `localizesenac`.`sala`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `localizesenac`.`sala` (
  `id` INT(11) NOT NULL,
  `fk_id_unidade` INT(11) NOT NULL,
  `andar` TINYINT(4) NOT NULL,
  `numero` INT(11) NOT NULL,
  `fk_id_categoria` INT(11) NOT NULL,
  PRIMARY KEY (`fk_id_unidade`, `andar`, `numero`),
  INDEX `fk_sala_unidade1_idx` (`fk_id_unidade` ASC),
  INDEX `fk_sala_categoria1_idx` (`fk_id_categoria` ASC),
  CONSTRAINT `fk_sala_categoria1`
    FOREIGN KEY (`fk_id_categoria`)
    REFERENCES `localizesenac`.`categoria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sala_unidade1`
    FOREIGN KEY (`fk_id_unidade`)
    REFERENCES `localizesenac`.`unidade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `localizesenac`.`aluno_disciplina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `localizesenac`.`aluno_disciplina` (
  `id` INT(11) NOT NULL,
  `dia_semana` CHAR(3) NOT NULL,
  `turno` CHAR(1) NOT NULL,
  `fk_id_aluno` INT(11) NOT NULL,
  `fk_sala_fk_id_unidade` INT(11) NOT NULL,
  `fk_andar_sala` TINYINT(4) NOT NULL,
  `fk_numero_sala` INT(11) NOT NULL,
  `fk_id_disciplina` INT(11) NOT NULL,
  INDEX `fk_aluno_disciplina_aluno1_idx` (`fk_id_aluno` ASC),
  INDEX `fk_aluno_disciplina_sala1_idx` (`fk_sala_fk_id_unidade` ASC, `fk_andar_sala` ASC, `fk_numero_sala` ASC),
  INDEX `fk_aluno_disciplina_disciplina1_idx` (`fk_id_disciplina` ASC),
  CONSTRAINT `fk_aluno_disciplina_aluno1`
    FOREIGN KEY (`fk_id_aluno`)
    REFERENCES `localizesenac`.`aluno` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aluno_disciplina_disciplina1`
    FOREIGN KEY (`fk_id_disciplina`)
    REFERENCES `localizesenac`.`disciplina` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aluno_disciplina_sala1`
    FOREIGN KEY (`fk_sala_fk_id_unidade` , `fk_andar_sala` , `fk_numero_sala`)
    REFERENCES `localizesenac`.`sala` (`fk_id_unidade` , `andar` , `numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `localizesenac`.`area_ensino`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `localizesenac`.`area_ensino` (
  `id` TINYINT(4) NOT NULL AUTO_INCREMENT,
  `fk_id_nivel` TINYINT(4) NOT NULL,
  `descricao` VARCHAR(80) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_id_nivel` (`fk_id_nivel` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `localizesenac`.`coordenadas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `localizesenac`.`coordenadas` (
  `id` INT(11) NOT NULL,
  `coordenada` DECIMAL(25,0) NOT NULL,
  `sala_fk_id_unidade` INT(11) NOT NULL,
  `sala_andar` TINYINT(4) NOT NULL,
  `sala_numero` INT(11) NOT NULL,
  PRIMARY KEY (`coordenada`),
  INDEX `fk_coordenadas_sala1_idx` (`sala_fk_id_unidade` ASC, `sala_andar` ASC, `sala_numero` ASC),
  CONSTRAINT `fk_coordenadas_sala1`
    FOREIGN KEY (`sala_fk_id_unidade` , `sala_andar` , `sala_numero`)
    REFERENCES `localizesenac`.`sala` (`fk_id_unidade` , `andar` , `numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `localizesenac`.`nivel_ensino`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `localizesenac`.`nivel_ensino` (
  `id` TINYINT(4) NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(40) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `localizesenac`.`curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `localizesenac`.`curso` (
  `id` INT(3) NOT NULL AUTO_INCREMENT,
  `fk_id_nivel_ensino` TINYINT(4) NOT NULL,
  `fk_id_area_ensino` TINYINT(4) NOT NULL,
  `descricao` VARCHAR(80) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_id_nivel_ensino` (`fk_id_nivel_ensino` ASC),
  INDEX `fk_id_area_ensino` (`fk_id_area_ensino` ASC),
  CONSTRAINT `fk_curso_nivel_ensino1`
    FOREIGN KEY (`fk_id_nivel_ensino`)
    REFERENCES `localizesenac`.`nivel_ensino` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `localizesenac`.`disciplina_curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `localizesenac`.`disciplina_curso` (
  `fk_id_disciplina` INT(11) NOT NULL,
  `fk_id_curso` INT(3) NOT NULL,
  INDEX `fk_disciplina_curso_disciplina1_idx` (`fk_id_disciplina` ASC),
  INDEX `fk_disciplina_curso_curso1_idx` (`fk_id_curso` ASC),
  CONSTRAINT `fk_disciplina_curso_curso1`
    FOREIGN KEY (`fk_id_curso`)
    REFERENCES `localizesenac`.`curso` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_disciplina_curso_disciplina1`
    FOREIGN KEY (`fk_id_disciplina`)
    REFERENCES `localizesenac`.`disciplina` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `localizesenac`.`evento_aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `localizesenac`.`evento_aluno` (
  `id` INT(11) NOT NULL,
  `descricao` VARCHAR(50) NOT NULL,
  `dia_semana` CHAR(3) NOT NULL,
  `fk_id_aluno` INT(11) NOT NULL,
  `fk_sala_fk_id_unidade` INT(11) NOT NULL,
  `fk_numero_sala` INT(11) NOT NULL,
  `fk_andar_sala` TINYINT(4) NOT NULL,
  `dt_inicio` DATE NOT NULL,
  `dt_final` DATE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_evento_aluno_aluno1_idx` (`fk_id_aluno` ASC),
  INDEX `fk_evento_aluno_sala1_idx` (`fk_sala_fk_id_unidade` ASC, `fk_andar_sala` ASC, `fk_numero_sala` ASC),
  CONSTRAINT `fk_evento_aluno_aluno1`
    FOREIGN KEY (`fk_id_aluno`)
    REFERENCES `localizesenac`.`aluno` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_evento_aluno_sala1`
    FOREIGN KEY (`fk_sala_fk_id_unidade` , `fk_andar_sala` , `fk_numero_sala`)
    REFERENCES `localizesenac`.`sala` (`fk_id_unidade` , `andar` , `numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `localizesenac`.`info_locais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `localizesenac`.`info_locais` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `imagem` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `email` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `telefone` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `horario` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `fk_sala_fk_id_unidade` INT(11) NOT NULL,
  `fk_andar_sala` TINYINT(4) NOT NULL,
  `fk_numero_sala` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_info_locais_sala1_idx` (`fk_sala_fk_id_unidade` ASC, `fk_andar_sala` ASC, `fk_numero_sala` ASC),
  CONSTRAINT `fk_info_locais_sala1`
    FOREIGN KEY (`fk_sala_fk_id_unidade` , `fk_andar_sala` , `fk_numero_sala`)
    REFERENCES `localizesenac`.`sala` (`fk_id_unidade` , `andar` , `numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `localizesenac`.`nivel_ensino_area`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `localizesenac`.`nivel_ensino_area` (
  `fk_id_area_ensino` TINYINT(4) NOT NULL,
  `fk_id_nivel_ensino` TINYINT(4) NOT NULL,
  INDEX `fk_nivelensinoarea_area_ensino1_idx` (`fk_id_area_ensino` ASC),
  INDEX `fk_nivelensinoarea_nivel_ensino1_idx` (`fk_id_nivel_ensino` ASC),
  CONSTRAINT `fk_nivelensinoarea_area_ensino1`
    FOREIGN KEY (`fk_id_area_ensino`)
    REFERENCES `localizesenac`.`area_ensino` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_nivelensinoarea_nivel_ensino1`
    FOREIGN KEY (`fk_id_nivel_ensino`)
    REFERENCES `localizesenac`.`nivel_ensino` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
